version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart:git nment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password